import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import { ptBR } from "@clerk/localizations";
import { CLientProviders } from "@/components/shared/client-providers";
import { setDefaultOptions } from "date-fns";
import { ptBR as dateFnsPtBr } from "date-fns/locale";

import "@/styles/globals.css";
import "@/styles/clerk.css";

setDefaultOptions({ locale: dateFnsPtBr });

const nunito = Nunito({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CodeLab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider 
      localization={ptBR}
      appearance={{variables: { colorPrimary: "hsl(160 100% 37%)" }}}
      >
      <html lang="pt-BR" suppressHydrationWarning>
        <body
          className={cn(nunito.variable, "antialiased font-sans dark")}>
          <CLientProviders>
            {children}
          </CLientProviders>
        </body>
      </html>
    </ClerkProvider>
  );
}
